### PR TITLE
Add support for optional fields

### PR DESCRIPTION
**Pull request by snikch**
I've done two things here which possibly makes this PR a bit muddy. Let me know if you'd like me to separate them.

* Replaced the deprecated `github.com/golang/protobuf/` packages with their `google.golang.org/protobuf/` equivalent
* Implemented support for the `optional` keyword which is now out of experimental support.

For the latter, this was a little confusing, but basically `optional` values are represented on the wire as `oneof`s (because a `oneof` is actually a set of `optional` fields where one must be present). Without any changes, optional fields were being treated as `oneof` fields, despite the appropriate `oneof` types not existing, which caused extra resolvers to be built and the generated code would not compile. The graphql definitions also had types as if the fields were `oneof`s. This means that when rendering, we need to skip the `oneof` output for these fields if they're "synthetic" oneofs (as the protobuf libraries refer to it).

See field `Proto3Optional ` here: https://pkg.go.dev/google.golang.org/protobuf@v1.27.1/types/descriptorpb#FieldDescriptorProto

### CODE REVIEW

**Comment by danielvladco** [comment]
Hi @snikch, Thanks for your PR.

I have a question, since you said that `optional` keyword is out of experimental support, why you still added the `--experimental_allow_proto3_optional` to the protoc commands?

I will do a more thorough review and merge in a few days.

**Comment by snikch** [comment]
Optional support was added as experimental in `protoc` in version `3.12`, then turned on by default in `3.15`. Because the install script for this repo is installing `3.13` it needs the experimental flag. We could bump the install script to a newer version and remove the experimental flags?
 
https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md
https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

**Comment by snikch** [comment]
Just bumping this :)

**Comment by snikch** [comment]
:heart: thanks @danielvladco!

**Pull request merged**
